[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
hideSidebarNav = false

[theme]
base = "dark"

# Yeni eklenen
[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true