[server]
headless = true
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[ui]
hideTopBar = true
hideSidebarNav = true

[theme]
base = "dark"

# Yeni eklenen
[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true