[server]
headless = true
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = fals

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[ui]
hideTopBar = false
hideSidebarNav = false

[theme]
base = "dark"

# Yeni eklenen
[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true