espn_s2 = "AEBGpUIA/AnKmAMeiwq2byxcqKI9YYYkT7KJaWfqBJj+XYjo6BX0WJkjskYvkQe7O3uyXwQwVotdoxWzjfKvff4GmQRQ186YtoYi/hmh/G2V2pnu+TsWU6vVf46CbathwR6FIvltM8d7BVYC8m0owPT1YWxF1tAwSdbWt+FRAdekC/u3VqskCGpA7L2lMoV5lpiV14BZu8A4aRVcen/RkkbTBU873fz/tl4rwCjOl0QXGkUDhxsJ/gIYWVWJhaGIovny9q/iMu8aNjWJptKwCQXgFvMjJyldMP/lPoPdydWuqg=="
swid = "{28BCA13D-E16C-4FB4-A5C2-1491BBF229EE}"
DB_HOST = "ep-withered-dawn-abvic60s-pooler.eu-west-2.aws.neon.tech"
DB_NAME = "neondb"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_PJ1mi5BCYDcs"
DB_PORT = 5432
GOOGLE_ANALYTICS_ID = "G-L36E2X2BQK"
